In [5]:
import numpy
arr01 = numpy.array([1,2,3,4,5])
type(arr01)

numpy.ndarray

In [6]:
import numpy as np
arr02 = np.array([1,2,3,4,5])
print(type(arr02))
print(arr02)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [7]:
arr03=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr03)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
L04 = [x for x in range(2,21,2)] #List Comprehension
print(L04)

arr04=np.array(L04)
print(arr04)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
L05 = [[2*x+3*y for x in range(2,21,2)] 
       for y in range(1,8)]

arr05=np.array(L05)
print(arr05)

print('Rows= ',np.size(arr05,axis=0),'Cols= ',np.size(arr05,axis=1))

[[ 7 11 15 19 23 27 31 35 39 43]
 [10 14 18 22 26 30 34 38 42 46]
 [13 17 21 25 29 33 37 41 45 49]
 [16 20 24 28 32 36 40 44 48 52]
 [19 23 27 31 35 39 43 47 51 55]
 [22 26 30 34 38 42 46 50 54 58]
 [25 29 33 37 41 45 49 53 57 61]]
Rows=  7 Cols=  10


In [10]:
print(arr05[5,5])
print(arr05[6,2])
print(arr05[1:4,3])
print(arr05[5,3:7])
print(arr05[2:5,3:7])
print(arr05[:,3:7])
print(arr05[2:4, :])
print(arr05[4:2:-1,6])

42
33
[22 25 28]
[34 38 42 46]
[[25 29 33 37]
 [28 32 36 40]
 [31 35 39 43]]
[[19 23 27 31]
 [22 26 30 34]
 [25 29 33 37]
 [28 32 36 40]
 [31 35 39 43]
 [34 38 42 46]
 [37 41 45 49]]
[[13 17 21 25 29 33 37 41 45 49]
 [16 20 24 28 32 36 40 44 48 52]]
[43 40]


In [11]:
print(arr05)

[[ 7 11 15 19 23 27 31 35 39 43]
 [10 14 18 22 26 30 34 38 42 46]
 [13 17 21 25 29 33 37 41 45 49]
 [16 20 24 28 32 36 40 44 48 52]
 [19 23 27 31 35 39 43 47 51 55]
 [22 26 30 34 38 42 46 50 54 58]
 [25 29 33 37 41 45 49 53 57 61]]


In [12]:
print(arr05[[1,3,5,6],
         [2,4,5,8]]) #arr ->[row,col]:  [1,2] , [3,4] , [5,5] , [6,8]

[18 32 42 57]


In [13]:
R,C=[1,3,5,6],[2,4,5,8]
print(arr05[R,C])

[18 32 42 57]


In [14]:
arr05= np.array([[1,2,3,4],
        [5,6,7,8]])
print(arr05)
print(np.add(arr05,5))
print(arr05+6) #wrapper add

[[1 2 3 4]
 [5 6 7 8]]
[[ 6  7  8  9]
 [10 11 12 13]]
[[ 7  8  9 10]
 [11 12 13 14]]


In [15]:
arr1=np.array([[1,2,3,4],
              [5,6,7,8]])
arr2=np.array([[10,9,8,7],
              [6,5,4,3]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2) #This is not matrix multiplication
print(arr1/arr2)

[[11 11 11 11]
 [11 11 11 11]]
[[-9 -7 -5 -3]
 [-1  1  3  5]]
[[10 18 24 28]
 [30 30 28 24]]
[[0.1        0.22222222 0.375      0.57142857]
 [0.83333333 1.2        1.75       2.66666667]]


In [16]:
# Creating Arrays
print(type(range(5)))
print(type(np.arange(5)))

print(np.arange(5))
print(np.arange(1,15))
print(np.arange(15,1,-1))


<class 'range'>
<class 'numpy.ndarray'>
[0 1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [17]:
arr06=np.linspace(1,2,10) #(a,b,c) by default c=50 points in between a and b
print(np.size(arr06)) #How many points
print(arr06)
print(np.linspace(10,1,5)) # reverse

10
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[10.    7.75  5.5   3.25  1.  ]


In [18]:
arr06=np.logspace(2,1,101) 
print(np.size(arr06)) 
print(arr06)

101
[100.          97.7237221   95.4992586   93.32543008  91.20108394
  89.12509381  87.096359    85.11380382  83.17637711  81.28305162
  79.43282347  77.62471166  75.8577575   74.13102413  72.44359601
  70.79457844  69.18309709  67.60829754  66.0693448   64.5654229
  63.09573445  61.65950019  60.25595861  58.88436554  57.54399373
  56.23413252  54.95408739  53.70317964  52.48074602  51.2861384
  50.11872336  48.97788194  47.86300923  46.77351413  45.70881896
  44.66835922  43.65158322  42.65795188  41.68693835  40.73802778
  39.81071706  38.9045145   38.01893963  37.15352291  36.30780548
  35.48133892  34.67368505  33.88441561  33.11311215  32.35936569
  31.6227766   30.90295433  30.1995172   29.51209227  28.84031503
  28.18382931  27.54228703  26.91534804  26.30267992  25.70395783
  25.11886432  24.54708916  23.98832919  23.44228815  22.90867653
  22.38721139  21.87761624  21.3796209   20.89296131  20.41737945
  19.95262315  19.498446    19.05460718  18.62087137  18.19700859
  17.782

In [19]:
print(np.random.rand())
print(np.random.rand(2,3)) #Random list with 2 row and 3 column

0.569908445440577
[[0.04059748 0.80700854 0.45405917]
 [0.18241271 0.30299968 0.05707459]]


In [20]:
#Gaussian Random number
print(np.random.randn())
print(np.random.randn(2,3))

0.7868667239559733
[[0.66733422 0.6502206  0.16248874]
 [1.43556913 1.05115923 1.5390144 ]]


In [21]:
AN = 6.023e23
print(AN)

6.023e+23


In [22]:
arr05=np.array([[1,2,3,4],
              [5,6,7,8]])
arr06=np.array([[10,9,8,7],
              [6,5,4,3]])
print(arr05>5)

[[False False False False]
 [False  True  True  True]]


In [23]:
arr07=np.array([[1,2,3,4],
              [5,6,7,8],
               [10,9,8,7]])

print("Sum = ",arr07.sum())

print("Max = ",arr07.max())
print("Min = ",arr07.min())

print("Average = ",arr07.mean())
print("Std. Dev = ",arr07.std())
print("Variance = ",arr07.var())
print("Rows Max = ",arr07.max(axis=1))
print("Cols Max = ",arr07.max(axis=0))

Sum =  70
Max =  10
Min =  1
Average =  5.833333333333333
Std. Dev =  2.733536577809454
Variance =  7.472222222222222
Rows Max =  [ 4  8 10]
Cols Max =  [10  9  8  8]


In [24]:
angleDeg = np.array([0,30,45,60,90,120,135,150,180])
angleRad = np.deg2rad(angleDeg)    #Convert degrees to Radian

print(angleDeg)
print(angleRad)

print(np.round(np.sin(angleRad),4))
print(np.round(np.cos(angleRad),4))
print(np.round(np.tan(angleRad),4))

#print(np.round(np.arcsin(angleRad),4))

[  0  30  45  60  90 120 135 150 180]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 2.35619449 2.61799388 3.14159265]
[0.     0.5    0.7071 0.866  1.     0.866  0.7071 0.5    0.    ]
[ 1.      0.866   0.7071  0.5     0.     -0.5    -0.7071 -0.866  -1.    ]
[ 0.00000000e+00  5.77400000e-01  1.00000000e+00  1.73210000e+00
  1.63312394e+16 -1.73210000e+00 -1.00000000e+00 -5.77400000e-01
 -0.00000000e+00]
