In [1]:
import numpy

arr=numpy.array([1,3,5,7,9])    # 1D Array
print(arr)
print(type(arr))     #ndarray means n dimensional array

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

#create 2D array
arr2D = np.array([[1,2,3],[4,5,6,]]) #Size should be same for nested lists 
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [5]:
print("hello")

hello


In [7]:
#create 1D array from list comprehension
import numpy as np

arr=np.array([x for x in range(2,21,2)]) #To create an array of even numbers from 2 to 20 using list comprehension
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
import numpy as np

arr=np.array([[3*x+2*y for y in range(5)] for x in range(10)]) 

#create 2D array from list comprehension
#first x will be 0 to 9 then for eaxh x : y will be frm 0 to 4 then applied on 3*x+2*y .. 
#for each x a row list is created

print(arr)

[[ 0  2  4  6  8]
 [ 3  5  7  9 11]
 [ 6  8 10 12 14]
 [ 9 11 13 15 17]
 [12 14 16 18 20]
 [15 17 19 21 23]
 [18 20 22 24 26]
 [21 23 25 27 29]
 [24 26 28 30 32]
 [27 29 31 33 35]]


In [15]:
import numpy as np

#extract first two row

arr2D = np.array([[1,2,3,7,9,55],[4,5,6,77,23,34],[81,2,23,75,92,17],[34,54,67,79,83,44]])
print("Original array\n",arr2D)
print("\nFirst two rows\n ",arr2D[:2])
print("\nAccessing an element of row 2 column 4 : ",arr2D[1][3])

#Printing a range of Array with the use of slicing method
sliced_arr=arr2D[:2,::2]
print(sliced_arr)

Original array
 [[ 1  2  3  7  9 55]
 [ 4  5  6 77 23 34]
 [81  2 23 75 92 17]
 [34 54 67 79 83 44]]

First two rows
  [[ 1  2  3  7  9 55]
 [ 4  5  6 77 23 34]]

Accessing an element of row 2 column 4 :  77
[[ 1  3  9]
 [ 4  6 23]]
