In [3]:
import numpy as np
l=[23,15,'day',5.5]
arr=np.array(l)
print(l)
print(arr)

#Array contains homogeneous data types

[23, 15, 'day', 5.5]
['23' '15' 'day' '5.5']


In [4]:
l=[x**2 for x in range(1,6)]
print(l)

#List comrehension

[1, 4, 9, 16, 25]


In [7]:
l2=np.array([[x*2+y*3 for y in range(5)] for x in range(10) ])
print(l2)

#List comprehension for 2D array

[[ 0  3  6  9 12]
 [ 2  5  8 11 14]
 [ 4  7 10 13 16]
 [ 6  9 12 15 18]
 [ 8 11 14 17 20]
 [10 13 16 19 22]
 [12 15 18 21 24]
 [14 17 20 23 26]
 [16 19 22 25 28]
 [18 21 24 27 30]]


In [14]:
#########################
# Basic Array Opeartions #

a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print('a=\n',a,'\nb=\n',b)

#Scalar addition subtraction
print("Adding 1 to every element of a:\n",a+1)
print("Subtracting 2 from every element of b:\n",b-2)

#Sum of array elements performing linear operations

print('Sum of array elements of a: ',a.sum())

#Adding two arrays performing binary operations
print(numbers,'\n')
print("Array sum (a+b):\n",a+b)

a=
 [[1 2]
 [3 4]] 
b=
 [[4 3]
 [2 1]]
Adding 1 to every element of a:
 [[2 3]
 [4 5]]
Subtracting 2 from every element of b:
 [[ 2  1]
 [ 0 -1]]
Sum of array elements of a:  10
Array sum (a+b):
 [[5 5]
 [5 5]]


In [44]:
#Create Integer array using np.arange()

import numpy as np
print(np.arange(5))
print(np.arange(5,10))
print(np.arange(1,10,3))
print(np.arange(10,1,-2))

[0 1 2 3 4]
[5 6 7 8 9]
[1 4 7]
[10  8  6  4  2]


In [23]:
import numpy as np
print(np.linspace(1.1,2.0,21))

#1/20=0.05 .. To create array of 21 elemements between 1 and 21 which are equally spaced

[1.1   1.145 1.19  1.235 1.28  1.325 1.37  1.415 1.46  1.505 1.55  1.595
 1.64  1.685 1.73  1.775 1.82  1.865 1.91  1.955 2.   ]


In [25]:
#Filling arrays with specific values using zeros,ones & full functions
import numpy as np
print(np.zeros(5))
print(np.ones(7))
print(np.full((3,5),13)) # 3X5 matrix with values=13

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [38]:
#Create arrays of Random numbers

import numpy as np

arr1= np.random.rand(5)
print("1D Floating-Point Array:\n",arr1)
arr2= np.random.rand(5,3)
print("\n2D Floating-Point Array:\n",arr2)

arr3= np.random.randint(10)
print("\nScalar :\n",arr3)
arr4= np.random.randint(10,size=5)
print("\n1D  Array:\n",arr4)
arr5= np.random.randint(10,size=(3,5))
print("\n2D  Array:\n",arr5)

1D Floating-Point Array:
 [0.32494957 0.77746559 0.39082816 0.30802661 0.32458787]

2D Floating-Point Array:
 [[0.45718024 0.91813112 0.99093895]
 [0.67859112 0.87841231 0.98150688]
 [0.99005928 0.49626262 0.75102164]
 [0.58255824 0.42515324 0.59165191]
 [0.71537428 0.88523631 0.27015642]]

Scalar :
 5

1D  Array:
 [6 6 3 0 5]

2D  Array:
 [[9 5 4 7 0]
 [1 3 9 4 0]
 [3 2 9 0 7]]


In [42]:
#Reshaping an array

import numpy as np

print(np.arange(1,16).reshape(3,5),'\n')
print(np.zeros(15).reshape(5,3),'\n')
print(np.ones(15).reshape(3,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
#Array Operators

import numpy as np

numbers = np.arange(1,6)
print(numbers,'\n')
print(numbers*2,'\n')
print(numbers*6.5,'\n')
print(numbers**2,'\n')

[1 2 3 4 5] 

[ 2  4  6  8 10] 

[ 6.5 13.  19.5 26.  32.5] 

[ 1  4  9 16 25] 



In [ ]:
#Arithmetic Operations between two arrays

In [46]:
#Comparing two Arrays
#It is performed elementwise

import numpy as np

a1=np.array([10,14,13,16,15])
a2=np.array([11,16,14,12,17])

print(a1,a2,sep='\n')

print(a1>=15)
print(a2==12)
print(a1<a2)


[10 14 13 16 15]
[11 16 14 12 17]
[False False False  True  True]
[False False False  True False]
[ True  True  True False  True]


In [52]:
#Numpy Calculation methods
# sum(),max(),min(),mean(),std(),var()

import numpy as np
grades=np.array([[87,96,70],
                 [100,87,90],
                 [94,77,90],
                 [100,81,82]])

print('Sum = ',grades.sum())
print('Max = ',grades.max())
print('Min = ',grades.min())
print('Average = ',grades.mean())
print('Std Dev = ',grades.std())
print('Variance = ',grades.var())

Sum =  1054
Max =  100
Min =  70
Average =  87.83333333333333
Std Dev =  8.792357792739987
Variance =  77.30555555555556


In [50]:
#Calculations by Row or Column
'''
axis=0 performs calculation on all row values within each column
axis=1 performs calculation on all clumn values within each row
'''

print('Max of cols = ',grades.max(axis=0))
print('Max of Rows = ',grades.max(axis=1))

Max of cols =  [100  96  90]
Max of Rows =  [ 96 100  94 100]
